name: Sync to CNB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Push
        run: |
          git remote add cnb https://cnb:${{ secrets.CNB_TOKEN }}@cnb.cool/CollapseLauncher/ReleaseRepo.git
          git push cnb main --force
