name: Upload to CNB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://github.com/CollapseLauncher/CollapseLauncher-ReleaseRepo.git .

      - name: Cleanup
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf .gitignore
          find . -type f -empty -delete
          find . -type d -empty -delete

      - name: Create package.json
        run: |
          cat > package.json << 'EOF'
          {
            "name": "collapse-launcher-release",
            "version": "1.0.0",
            "license": "MIT",
            "description": "Collapse Launcher Release",
            "repository": {
              "type": "git",
              "url": "git+https://github.com/CollapseLauncher/CollapseLauncher-ReleaseRepo.git"
            }
          }
          EOF

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Publish
        env:
          BUN_AUTH_TOKEN: ${{ secrets.CNB_TOKEN }}
        run: |
          bun publish --force --registry=https://npm.cnb.cool/CollapseLauncher/release/-/packages/
