name: Upload to R2
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Upload-to-R2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          path: cl-cdn
          
      - name: cleanup
        run: |
          rm -rf ./cl-cdn/.git
          rm -rf ./cl-cdn/.github
          rm -rf ./cl-cdn/.gitignore
          rm -rf ./cl-cdn/LICENSE
          rm -rf ./cl-cdn/pack.bat
          rm -rf ./cl-cdn/start_reindex.bat

      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: cl-cdn
          destination-dir: cl-cdn
          output-file-url: false
        continue-on-error: true

      - name: Purge Cloudflare cache
        run: |
            curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_PURGE_CACHE_ZONEID }}/purge_cache" \
                -H "Authorization: Bearer ${{ secrets.CF_PURGE_CACHE_TOKEN }}" \
                -H "Content-Type: application/json" \
                --data "{ \"purge_everything\": true }"